version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel12-app
        volumes:
            - .:/var/www
        networks:
            - laravel
        ports:
            - "9000:9000"

    nginx:
        image: nginx:alpine
        container_name: laravel12-nginx
        ports:
            - "8020:8020"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
