name: Build the application and store on GitHub Registry
on:
  push:
    branches: main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  setup:
    name: Setup components
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./pixel-positions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: composer:v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock')}}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Upload vendor directory
        uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: pixel-positions/vendor/

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
      - run: npm install
      - run: npm run build --if-present
        env:
          APP_URL: https://pixel.tomemming.nl

      - name: Upload built assets
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: pixel-positions/public/build/


  build-and-push:
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./pixel-positions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download vendor directory
        uses: actions/download-artifact@v4
        with:
          name: vendor
          path: pixel-positions/vendor/

      - name: Download built assets
        uses: actions/download-artifact@v4
        with:
          name: assets
          path: pixel-positions/public/build/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build prod image
        run: |
          docker build \
            --target prod \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            .

      - name: Push prod image to GitHub Container Registry
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest